jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Build

  steps:

  - script: |
      chmod +x gradlew
    displayName: 'Permisos de Escritura'
    
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    displayName: Build
